#!_usr_bin_env python3
# -*- coding:utf-8 -*-
# Copyright (c) Megvii, Inc. and its affiliates.

VOC_CLASSES = (
    "sneakers", "hat", "bottle", "cup", "glasses", "handbag", "book", "plate", "helmet", "leather shoes", "pillow",
    "glove", "potted plant", "bracelet", "flower", "storage box", "plants pot_vase", "bench", "wine glass", "boots",
    "umbrella", "trash bin_can", "stool", "backpack", "belt", "barrel_bucket", "bowl", "slippers", "basket",
    "towel_napkin", "toy", "tie", "pen_pencil", "microphone", "sandals", "canned", "necklace", "high heels", "bread",
    "combine with bowl", "watch", "apple", "camera", "stuffed animal", "cake", "knife", "cell phone", "power outlet",
    "clock", "drum", "fork", "hanger", "pot_pan", "tea pot", "spoon", "balloon", "banana", "orange", "soccer",
    "combine with glove", "paper towel", "shampoo_shower gel", "tomato", "pizza", "tangerine", "toiletries", "lemon",
    "donut", "liquid soap", "broccoli", "pumpkin", "tissue", "cookies", "candy", "scissors", "folder", "baseball",
    "carrot", "bow tie", "strawberry", "grapes", "american football", "basketball", "pear", "billiards", "pepper",
    "potato", "sausage", "chopsticks", "pie", "tong", "toothbrush", "egg", "bar soap", "earphone", "brush", "key",
    "hammer", "pliers", "screwdriver", "toothpaste", "shrimp", "poker card", "radish", "Bread_bun", "crab", "baozi",
    "lighter", "comb", "seal", "eraser", "pencil case"
)

# VOC_CLASSES = (
#     'sneakers', 'hat', 'bottle', 'cup', 'glasses', 'handbag', 'book', 'plate', 'helmet', 'leather shoes', 'pillow',
#     'glove', 'potted plant', 'bracelet', 'flower', 'storage box', 'plants pot_vase', 'bench', 'wine glass', 'boots',
#     'umbrella',
#     'trash bin_can', 'stool', 'backpack', 'belt', 'basket', 'towel_napkin', 'slippers', 'bowl', 'barrel_bucket', 'toy',
#     'tie', 'pen_pencil', 'microphone', 'sandals', 'canned', 'necklace', 'bread', 'high heels', 'watch',
#     'combine with bowl', 'apple', 'camera', 'stuffed animal', 'cake', 'knife', 'cell phone', 'power outlet', 'clock',
#     'drum', 'fork', 'hanger', 'pot_pan', 'tea pot', 'spoon', 'balloon', 'orange', 'banana', 'soccer',
#     'combine with glove',
#     'paper towel', 'tomato', 'shampoo_shower gel', 'donut', 'tangerine', 'pizza', 'toiletries', 'broccoli', 'lemon',
#     'liquid soap', 'pumpkin', 'tissue', 'carrot', 'cookies', 'candy', 'scissors', 'folder', 'baseball', 'strawberry',
#     'bow tie', 'pepper', 'grapes', 'pear', 'american football', 'basketball', 'potato', 'billiards', 'sausage',
#     'tennis ball', 'chopsticks', 'pie', 'frisbee', 'hamburger', 'cucumber', 'tong', 'hot dog', 'toothbrush',
#     'facial cleanser', 'mango', 'egg', 'onion', 'ice cream', 'plum', 'bar soap', 'watermelon', 'cabbage', 'golf ball',
#     'pine apple', 'peach', 'notepaper', 'green beans', 'brush', 'earphone', 'garlic', 'french fries', 'avocado',
#     'sandwich', 'kiwi fruit', 'cherry', 'tablet', 'green vegetables', 'nuts', 'corn', 'key', 'screwdriver', 'broom',
#     'pliers',
#     'hammer', 'volleyball', 'eggplant', 'dates', 'rice', 'dumbbell', 'hamimelon', 'stapler', 'lettuce', 'meat balls',
#     'toothpaste', 'shrimp', 'pomegranate', 'coconut', 'mushroom', 'calculator', 'egg tart', 'cheese', 'pomelo',
#     'papaya',
#     'green onion', 'chips', 'spring rolls', 'steak', 'poker card', 'radish', 'noodles', 'crab', 'Bread_bun', 'baozi',
#     'lighter',
#     'mangosteen', 'seal', 'comb', 'eraser', 'pitaya', 'scallop', 'pencil case', 'table tennis  paddle', 'okra',
#     'durian', 'asparagus', 'pasta', 'lobster', 'flashlight'
# )

# VOC_CLASSES = ( '__background__', # always index 0
# VOC_CLASSES = (
    # "aeroplane",
    # "bicycle",
    # "bird",
    # "boat",
    # "bottle",
    # "bus",
    # "car",
    # "cat",
    # "chair",
    # "cow",
    # "diningtable",
    # "dog",
    # "horse",
    # "motorbike",
    # "person",
    # "pottedplant",
    # "sheep",
    # "sofa",
    # "train",
    # "tvmonitor",
# )

# VOC_CLASSES = ('human', 'sneakers', 'chair', 'hat', 'lamp', 'bottle', 'cabinet_shelf', 'cup', 'car', 'glasses',
#                'picture_frame', 'desk', 'handbag', 'street lights', 'book', 'plate', 'helmet', 'leather shoes',
#                'pillow',
#                'glove', 'potted plant', 'bracelet', 'flower', 'monitor', 'storage box', 'plants pot_vase', 'bench',
#                'wine glass', 'boots', 'dining table', 'umbrella', 'boat', 'flag', 'speaker', 'trash bin_can', 'stool',
#                'backpack', 'sofa', 'belt', 'carpet', 'basket', 'towel_napkin', 'slippers', 'bowl', 'barrel_bucket',
#                'coffee table', 'suv', 'toy', 'tie', 'bed', 'traffic light', 'pen_pencil', 'microphone', 'sandals',
#                'canned',
#                'necklace', 'mirror', 'faucet', 'bicycle', 'bread', 'high heels', 'ring', 'van', 'watch',
#                'combine with bowl', 'sink', 'horse', 'fish', 'apple', 'traffic sign', 'camera', 'candle',
#                'stuffed animal',
#                'cake', 'motorbike_motorcycle', 'wild bird', 'laptop', 'knife', 'cell phone', 'paddle', 'truck', 'cow',
#                'power outlet', 'clock', 'drum', 'fork', 'bus', 'hanger', 'nightstand', 'pot_pan', 'sheep', 'guitar',
#                'traffic cone', 'tea pot', 'keyboard', 'tripod', 'hockey stick', 'fan', 'dog', 'spoon',
#                'blackboard_whiteboard', 'balloon', 'air conditioner', 'cymbal', 'mouse', 'telephone', 'pickup truck',
#                'orange', 'banana', 'airplane', 'luggage', 'skis', 'soccer', 'trolley', 'oven', 'remote',
#                'combine with glove', 'paper towel', 'refrigerator', 'train', 'tomato', 'machinery vehicle', 'tent',
#                'shampoo_shower gel', 'head phone', 'lantern', 'donut', 'cleaning products', 'sailboat', 'tangerine',
#                'pizza', 'kite', 'computer box', 'elephant', 'toiletries', 'gas stove', 'broccoli', 'toilet', 'stroller',
#                'shovel', 'baseball bat', 'microwave', 'skateboard', 'surfboard', 'surveillance camera', 'gun',
#                'Life saver',
#                'cat', 'lemon', 'liquid soap', 'zebra', 'duck', 'sports car', 'giraffe', 'pumpkin',
#                'Accordion_keyboard_piano', 'radiator', 'converter', 'tissue', 'carrot', 'washing machine', 'vent',
#                'cookies', 'cutting_chopping board', 'tennis racket', 'candy', 'skating and skiing shoes', 'scissors',
#                'folder', 'baseball', 'strawberry', 'bow tie', 'pigeon', 'pepper', 'coffee machine', 'bathtub',
#                'snowboard',
#                'suitcase', 'grapes', 'ladder', 'pear', 'american football', 'basketball', 'potato', 'paint brush',
#                'printer', 'billiards', 'fire hydrant', 'goose', 'projector', 'sausage', 'fire extinguisher',
#                'extension cord', 'facial mask', 'tennis ball', 'chopsticks', 'Electronic stove and gas stove', 'pie',
#                'frisbee', 'kettle', 'hamburger', 'golf club', 'cucumber', 'clutch', 'blender', 'tong', 'slide',
#                'hot dog',
#                'toothbrush', 'facial cleanser', 'mango', 'deer', 'egg', 'violin', 'marker', 'ship', 'chicken', 'onion',
#                'ice cream', 'tape', 'wheelchair', 'plum', 'bar soap', 'scale', 'watermelon', 'cabbage', 'router_modem',
#                'golf ball', 'pine apple', 'crane', 'fire truck', 'peach', 'cello', 'notepaper', 'tricycle', 'toaster',
#                'helicopter', 'green beans', 'brush', 'carriage', 'cigar', 'earphone', 'penguin', 'hurdle', 'swing',
#                'radio',
#                'CD', 'parking meter', 'swan', 'garlic', 'french fries', 'horn', 'avocado', 'saxophone', 'trumpet',
#                'sandwich', 'cue', 'kiwi fruit', 'bear', 'fishing rod', 'cherry', 'tablet', 'green vegetables', 'nuts',
#                'corn', 'key', 'screwdriver', 'globe', 'broom', 'pliers', 'hammer', 'volleyball', 'eggplant', 'trophy',
#                'board eraser', 'dates', 'rice', 'tape measure_ruler', 'dumbbell', 'hamimelon', 'stapler', 'camel',
#                'lettuce', 'goldfish', 'meat balls', 'medal', 'toothpaste', 'antelope', 'shrimp', 'rickshaw', 'trombone',
#                'pomegranate', 'coconut', 'jellyfish', 'mushroom', 'calculator', 'treadmill', 'butterfly', 'egg tart',
#                'cheese', 'pomelo', 'pig', 'race car', 'rice cooker', 'tuba', 'crosswalk sign', 'papaya', 'hair dryer',
#                'green onion', 'chips', 'dolphin', 'sushi', 'urinal', 'donkey', 'electric drill', 'spring rolls',
#                'tortoise_turtle', 'parrot', 'flute', 'measuring cup', 'shark', 'steak', 'poker card', 'binoculars',
#                'llama',
#                'radish', 'noodles', 'mop', 'yak', 'crab', 'microscope', 'barbell', 'Bread_bun', 'baozi', 'lion',
#                'red cabbage', 'polar bear', 'lighter', 'mangosteen', 'seal', 'comb', 'eraser', 'pitaya', 'scallop',
#                'pencil case', 'saw', 'table tennis  paddle', 'okra', 'starfish', 'monkey', 'eagle', 'durian', 'rabbit',
#                'game board', 'french horn', 'ambulance', 'asparagus', 'hoverboard', 'pasta', 'target', 'hotair balloon',
#                'chainsaw', 'lobster', 'iron', 'flashlight'
#                )
